apiVersion: batch/v1
kind: CronJob
metadata:
  name: diagrams-repo-runner
  namespace: jovian-prod
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            connection: standard
          containers:
          - name: diagrams-repo-runner
            image: aegisfatedh/diagrams-repo-runner:main
            env:
              - name: GIT_REPO
                valueFrom:
                  secretKeyRef:
                    name: diagrams-repo-runner-secrets
                    key: git_repo
              - name: GIT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: diagrams-repo-runner-secrets
                    key: git_token
              - name: GIT_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: diagrams-repo-runner-secrets
                    key: git_username
              - name: DRY_RUN
                value: "no"
      backoffLimit: 3
