apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden-backup
  namespace: jovian-prod
spec:
  # The PVC to be backed up
  sourcePVC: vw-pvc
  trigger:
    # Take a backup every day at 5am
    schedule: "0 5 * * *"
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 14
    # Name of the Secret with the connection information
    repository: restic-vaultwarden
    # Retention policy for backups
    retain:
      daily: 7
    # Snapshot the source volume prior to taking a backup to ensure a point-in-time image.
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephfsplugin-snapclass