apiVersion: apps/v1
kind: Deployment
metadata:
  name: littlelink
  namespace: jovian-prod
  labels:
    app: littlelink
    service: content
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: littlelink
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: littlelink
    spec:
      nodeSelector:
        connection: standard
      containers:
      - name: littlelink
        image: ghcr.io/timothystewart6/littlelink-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: littlelink-http
          protocol: TCP
        env:
        - name: META_TITLE
          value: 'Sch-Apps'
        - name: META_DESCRIPTION
          value: 'SRE | Nerd | Homelabber | Gamer'
        - name: META_AUTHOR
          value: 'Stephen Hudgins'
        - name: META_KEYWORDS
          value: 'Homelab, Engineering, Observability, Kubernetes'
        - name: META_INDEX_STATUS
          value: 'all'
        - name: LANG
          value: 'en'
        - name: THEME
          value: 'Auto'
        - name: BIO
          value: 'Homelabber | Tech enthusiast | Car guy | Planespotter | Railfan | Gamer | Nerd next door'
        - name: OG_SITE_NAME
          value: 'Sch-Apps'
        - name: OG_TITLE
          value: 'Sch-Apps'
        - name: OG_DESCRIPTION
          value: 'The hub for all things in my Homelab'
        - name: OG_URL
          value: 'https://home.sch-apps.com'
        - name: OG_IMAGE
          value: 'https://raw.githubusercontent.com/aegis-fate-gh/homelab/refs/heads/main/images/littlelink/profile_400.jpg'
        - name: OG_IMAGE_WIDTH
          value: '400'
        - name: OG_IMAGE_HEIGHT
          value: '400'
        - name: FAVICON_URL
          value: 'https://raw.githubusercontent.com/aegis-fate-gh/homelab/refs/heads/main/images/littlelink/profile_200.jpg'
        - name: AVATAR_URL
          value: 'https://raw.githubusercontent.com/aegis-fate-gh/homelab/refs/heads/main/images/littlelink/profile_200.jpg'
        - name: AVATAR_2X_URL
          value: 'https://raw.githubusercontent.com/aegis-fate-gh/homelab/refs/heads/main/images/littlelink/profile_400.jpg'
        - name: AVATAR_ALT
          value: 'Stephen Hudgins Profile Pic'
        - name: NAME
          value: 'Stephen Hudgins'
        - name: STEAM
          value: 'https://steamcommunity.com/profiles/76561198021708921/'
        - name: GITHUB
          value: 'https://github.com/aegis-fate-gh'
        - name: INSTAGRAM
          value: 'https://www.instagram.com/aegis.fate?igsh=bng5MDBsbHR6M3Zm&utm_source=qr'
        - name: LINKED_IN
          value: 'https://www.linkedin.com/in/stephen-hudgins-24743829/'
        - name: BUYMEACOFFEE
          value: 'https://buymeacoffee.com/aegis.fate'
        - name: YOUTUBE
          value: 'https://youtube.com/@stephenh2?si=4UopZFLd-sa2cxL2'
        - name: FOOTER
          value: 'Stephen Hudgins © 2025'
