apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapotter-pvc
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: 10Gi
