apiVersion: v1
kind: Service
metadata:
  name: snapotter-service
  namespace: jovian-prod
spec:
  selector:
    app: snapotter
  ports:
    - port: 1349
      targetPort: snapotter-http
      protocol: TCP
      name: snapotter-http
