apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-app
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-postgres
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-redis
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: 1Gi