apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: jovian-prod
  labels:
    app: n8n
    service: n8n
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: n8n
    spec:
      nodeSelector:
        connection: standard
      initContainers:
        - name: volume-permissions-fix
          image: busybox:latest
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
          - name: n8n-config
            mountPath: /data
          securityContext:
            runAsUser: 0  # Must run as root to perform chown
      containers:
      - name: postgres
        image: docker.io/library/postgres:18
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: n8n-db
          protocol: TCP
        volumeMounts:
        - name: n8n-db-config
          mountPath: /var/lib/postgresql
        env:
        - name: TZ
          value: 'America/Chicago'
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: n8n_postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: n8n_postgres_password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: n8n_postgres_db
      - name: n8n
        image: aegisfatedh/n8n-custom:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 5678
          name: n8n-http
          protocol: TCP
        env:
        - name: TZ
          value: 'America/Chicago'
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: DB_TYPE
          value: 'postgresdb'
        - name: DB_POSTGRESDB_HOST
          value: 'localhost'
        - name: DB_POSTGRESDB_PORT
          value: '5432'
        - name: DB_POSTGRESDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: n8n_postgres_db
        - name: DB_POSTGRESDB_USER
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: n8n_postgres_user
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: n8n_postgres_password
        - name: N8N_RUNNERS_MODE
          value: 'external'
        - name: N8N_RUNNERS_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: n8n_runners_auth_token
        - name: N8N_RUNNERS_BROKER_LISTEN_ADDRESS
          value: '0.0.0.0'
        - name: N8N_EXECUTE_COMMAND
          value: 'true'
        - name: NODES_EXCLUDE
          value: '[]'
        - name: NODE_FUNCTION_ALLOW_BUILTIN
          value: '*'
        - name: NODE_FUNCTION_ALLOW_EXTERNAL
          value: 'exiftool-vendored'
        - name: N8N_RUNNERS_EXTERNAL_ALLOW
          value: '*'
        volumeMounts:
        - name: n8n-config
          mountPath: /home/node/.n8n
      - name: n8n-runner
        image: n8nio/runners:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 5679
          name: n8n-runner-task
          protocol: TCP
        env:
        - name: TZ
          value: 'America/Chicago'
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: N8N_RUNNERS_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: n8n_runners_auth_token
        - name: N8N_RUNNERS_TASK_BROKER_URI
          value: 'http://localhost:5679'
        - name: NODE_FUNCTION_ALLOW_BUILTIN
          value: '*'
        - name: NODE_FUNCTION_ALLOW_EXTERNAL
          value: 'exiftool-vendored'
        - name: N8N_RUNNERS_STDLIB_ALLOW
          value: '*'
      volumes:
      - name: n8n-config
        persistentVolumeClaim:
          claimName: n8n-pvc
          readOnly: false
      - name: n8n-db-config
        persistentVolumeClaim:
          claimName: n8n-db-pvc
          readOnly: false
      - name: db-init-config
        configMap:
          name: n8n-db-config
