apiVersion: batch/v1
kind: CronJob
metadata:
  name: media-pruner
  namespace: jovian-prod
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 7200
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          nodeSelector:
            connection: standard
          containers:
          - name: media-pruner
            image: busybox:latest
            command: ["/bin/sh", "-c"] 
            args: ["find /media/downloads/completed/tv-sonarr -mtime +7"]
            imagePullPolicy: Always
            volumeMounts:
            - name: media
              mountPath: /media
          volumes:
          - name: media
            persistentVolumeClaim:
              claimName: prune-smb-media-pvc
          restartPolicy: OnFailure