apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: INSERT_NAME_HERE
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: CHANGE_ME