apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: CHANGE_ME
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-csi-media
  resources:
    requests:
      storage: 72Ti
  volumeName: CHANGE_ME
