apiVersion: v1
kind: Service
metadata:
  name: iperf3
  namespace: jovian-prod
  annotations:
    metallb.io/address-pool: prod-pool
    metallb.io/loadBalancerIPs: 192.168.6.210
    argocd.argoproj.io/sync-wave: "0"
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 5201
    targetPort: input
    name: input
  selector:
    name: iperf3
  type: LoadBalancer