apiVersion: v1
kind: service
metadata:
  name: iperf3-service
  namespace: jovian-prod
  annotations:
    metallb.io/address-pool: prod-pool
    metallb.io/loadBalancerIPs: 192.168.6.210
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 5201
    targetPort: input
    name: input
  selector:
    app: iperf3
  type: LoadBalancer