apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: CHANGE_ME
  namespace: jovian-prod
spec:
  # The PVC to be backed up
  sourcePVC: CHANGE_ME
  trigger:
    # Take a backup every day at 1am to avoid 2am internal DB backups
    schedule: "CHANGE_ME"
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 14
    # Name of the Secret with the connection information
    repository: CHANGE_ME
    # Retention policy for backups
    retain:
      daily: 7
    # Snapshot the source volume prior to taking a backup to ensure a point-in-time image.
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-cephfsplugin-snapclass