apiVersion: v1
kind: ConfigMap
metadata:
  name: kometa-concerts-config
  namespace: jovian-prod
data:
  concerts.yml: |
    metadata:
      Ace Combats The Symphony 25th Anniversary:
        match:
          title: Ace Combats the Symphony 25th Anniversary
        sort_title: Ace Combats The Symphony 25th Anniversary
        originally_available: 2021-08-07
        summary: | 
          Conductor: Keiki Kobayashi
          Performed by: ACE COMBAT 25th anniversary AIR TACTICAL ORCHESTRA
          ACE COMBAT/S THE SYMPHONY 25TH ANNIVERSARY - A Full-blown musical event conducted solely for our brand game, “ACE COMBAT”
          Our first concert was held on July 27, 2019 at Haneda Airport “TIAT SKY HALL” and received quite a favorable reception. We would like our audience to enjoy popular pieces of the music from “ACE COMBAT” with full orchestra performance and behind-the-scenes stories revealed by our producers. They will be able to see new sides of ACE COMBAT series.
          We will offer you online distribution of the movie of our acclaimed concert which was held in Japan (at Ota Citizen Hall in Kamata) on August 7, 2021.
      Star Trek Concert Prague 02 11 2016:
        match:
          title: Star Trek Concert - Prague - 2-11-2016
        sort_title: Star Trek Concert - Prague - 2-11-2016
        originally_available: 2016-02-08
        summary: "Film Music Prague Festival produced STAR TREK CONCERT which was a celebration of 50th Anniversary of this franchise. (www.filmmusicprague.com)"
      The Witch From Mercury and Asticassia Music Video:
        match:
          title: The Witch from Mercury and Asticassia
        sort_title: The Witch from Mercury and Asticassia
        originally_available: 2022-12-04
        summary: |
          "The Witch From Mercury" is the main theme song and the title song of Mobile Suit Gundam The Witch from Mercury. "Asticassia" is named from the school, which is the sub-theme and the stage of the story.
          Music by Takashi Ohmama
      REQUIEM FOR ATTACK ON TITAN Grissini Project Orchestra:
        match:
          title: Requiem for Attack on Titan Grissini Project Orchestra
        sort_title: Requiem for Attack on Titan Grissini Project Orchestra
        originally_available: 2023-11-02
        summary: |
          Symphonic suit for vocalist, choir, piano trio, organ and orchestra
          Music by Hiroyuki Sawano and Linked Horizon. Arrangement and orchestration Simon Nebout
          GRISSINI PROJECT ORCHESTRA - Presented by Romain Vaudé
      Hiroyuki Sawano MOBILE SUIT GUNDAM UNICORN Suite:
        match:
          title: Hiroyuki Sawano Mobile Suit Gundam Unicorn Suite
        sort_title: Hiroyuki Sawano Mobile Suit Gundam Unicorn Suite
        originally_available: 2021-04-13
        summary: |
          On May 7, Hiroyuki Sawano, who is in charge of music at the national road show "Mobile Suit Gundam: Hathaway of the Flash", released a new MV.
          This song recorded the music in the play of "Mobile Suit Gundam Unicorn" as a sume, and the MV was shot in front of the full-sized "Moving Gundam" of "GUNDAM FACTORY YOKOHAMA".
          0:13 UNICORN GUNDAM
          3:36 MOBILE SUIT
          6:26 EGO
          9:42 MOBILE ARMOR
          13:02 ON YOUR MARK
      Hiroyuki Sawano Project emU Attack on Titan Suite:
        match:
          title: Hiroyuki Sawano Project emU Attack on Titan Suite
        sort_title: Hiroyuki Sawano Project emU Attack on Titan Suite
        originally_available: 2020-10-02
        summary: |
          Project【emU】is the soundtrack revival project by Hiroyuki Sawano.
          In this time, he has arranged a suite of music for the soundtrack of the TV animation “Attack on Titan” which is the work he composed.
          0:12 Attack on Titan
          4:26 Before Lights Out
          7:06 K2
          9:20 T:T
          12:32 Counter Attack-Mankind
          15:37 Apple Seed
      Daft Punk Orchestra Medley:
        match:
          title: Daft Punk Orchestra Medley
        sort_title: Daft Punk Orchestra Medley
        originally_available: 2020-03-08
        summary: |
          Source: Youtube
          Creator: Kaleidoscope Orchestra
          Description: We had so many people request a Daft Punk medley, so here it is! We had lots of fun recording this one back in February!

          Orchestration by Steve Pycroft
          Recorded by Mark Lewis & Thomas Dibb
          Audio Mixed & Video Edited by Steve Pycroft
          Mastered by Steve Pycroft
          Video shot by Steve Pycroft & Mark Lewis

          0:00 Robot Rock
          1:00 Harder, Better, Faster, Stronger
          2:28 Something About Us
          2:45 Aerodynamic
          3:52 One More Time
          4:58 Doin' it Right
          6:00 Around the World
          7:11 Robot Rock

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kometa-web-video-config
  namespace: jovian-prod
data:
  web_video.yml: |
    metadata:
      Back to the Barn - Penultimate Star Trek short shot:
        match:
          title: Back to the Barn - Penultimate Star Trek short shot
        sort_title: Back to the Barn - Penultimate Star Trek short shot
        originally_available: 2026-03-14
        summary: |
          Source: Youtube
          Creator: Howard Day
          Description: Whew. This is by far the longest shot of this short, and I'm delighted I was able to render all this out. At 1540 frames long, it's a true monster. Best of all? This isn't the final version of this! I have to re-render it again! Holy crap! The next one should be awesome and final, tho. I'm also excited to be using an actual Voice Actor for the Captains Log now! The wonderful audio was done by Baldwin Williams Jr. - you can find his website below. Enjoy!
        collection: [ Star Trek, Short Film, YouTube, Howard Day ]
      Bali Real 8K HDR:
        match:
          title: Bali 8K HDR
        sort_title: Bali 8K HDR
        originally_available: 2021-02-03
        summary: |
          Source: Youtube
          Creator: Around The World 4K
          Description: Paradise means different things to different people, yet, the term paradise often gets mentioned together with Bali. A magical blend of culture, people, nature, activities, weather, culinary delights, nightlife, and beautiful accommodation. Bali is rated as one of the best travel destinations in the world.
        collection: [ Around the World ]
      Budapest 8K:
        match:
          title: Budapest 8K
        sort_title: Budapest 8K
        originally_available: 2019-03-25
        summary: |
          Source: YouTube
          Creator: Around The World 4K
          Description: Exploring Budapest, our first 8K resolution short film on our YouTube Channel. It's been a while now since the last posting but we're back with a completely new level of quality using professional Hollywood RED Digital Cinema cameras. Since this is our second video of the beautiful city of Budapest, we tried something new.
        collection: [ Around the World ]
      Rendezvous:
        match:
          title: rendezvous
        sort_title: Rendezvous
        title: Rendezvous
        originally_available: 1976-09-17
        summary: |
          C'était un rendez-vous - Paris, 5:30 AM, 15th of August, 1976. As the night's dimming lights yield to dawn, a mighty mechanical roar cuts through the silence. It is the unmistakable sound of a Ferrari 275 GTB V-12 engine, revving and shifting gears as it furiously enters the tunnel at Porte Dauphine. Exiting flat out onto the Avenue des Champs-Élysées, the mysterious driver aims for the Place de la Concorde and the Palais Garnier, downshifting in a mad dash through the heart of the city. As the car enters narrow, cobbled streets, the tyres squeal, scattering pigeons and startled pedestrians alike. Now, this heart-pounding, nerve-wracking drive continues towards the Place Pigalle. With the Basilique du Sacré-Coeur as the final destination and one blind hairpin left that could turn one's hair grey, the daring driver finally reaches the end of this adrenaline-filled ride. But who is waiting for him at the finish line?
        collection: [ Short Film, Ferrari, Paris ]
      Reaching for the skies (Star Trek fan animation):
        match:
          title: Reaching for the skies (Star Trek fan animation)
        sort_title: Reaching for the skies (Star Trek fan animation)
        originally_available: 2019-09-29
        summary: |
          Source: YouTube
          Creator: Alvision100
          Description: Here are some more animations I composited. Most of these renderings are NON-CANON and represent my humble vision of a fan-made universe I like to call Sky-verse. Thank you for watching! Special thanks to Ricky Wallace for his inspiration. The amazing musical score on this video is composed by Scott Buckley. I can't thank him enough for allowing the use of this track. Feel free to check out my other videos. Live long and prosper and be safe. 🖖
          Music 'Icarus' by Scott Buckley
        collection: [ Short Film, Star Trek ]
      Gran Turismo 5 Tribute to Ferrari 458 Italia:
        match:
          title: Gran Turismo 5 Tribute to Ferrari 458 Italia
        sort_title: Gran Turismo 5 Tribute to Ferrari 458 Italia
        originally_available: 2009-09-29
        summary: |
          Source: YouTube
          Creator: Hospital Records
          Description: The "Ferrari 458 Italia" debuted at the Frankfurt Motor Show on September 2009. This is a movie made in collaboration between "Gran Turismo" and Ferrari, that explores the allure of Ferrari's newest V8 Berlinetta.
          The power output of Ferrari's first direct injection V8 unit to be mounted in their midship supercar, reaches an amazing 570ps. This next generation power performance and the flowing bodywork by Pininfarina comes together to produce a car that achieves a maximum speed of 325km/h.
        collection: [ Gaming, Ferrari, Gran Turismo, Gran Turismo 5 ]
      Gran Turismo 6 - Opening Movie & Launch Trailer:
        match:
          title: GT6 Opening Video
        sort_title: Gran Turismo 6 - Opening Movie & Launch Trailer
        originally_available: 2013-12-05
        summary: |
          Source: YouTube
          Creator: Playstation
          Description: The opening to Gran Turismo 6
        collection: [ Gaming, Gran Turismo, Gran Turismo 6 ]
      The 500 Series Shinkansen Nozomi Ver4:
        match:
          title: 39_500v4_090301
        sort_title: The 500 Series Shinkansen Nozomi Ver.4
        title: The 500 Series Shinkansen Nozomi Ver.4
        originally_available: 2009-03-01
        summary: |
          Source: Web
          Creator: aidusl
          Description: The 500 Series Shinkansen are the fastest, most powerful and most expensive trainsets yet to run on Japan's Shinkansen high-speed rail network. They are designed to be capable of 320 km/h (200 mph) although they operate at a maximum of 300 km/h (186 mph) in service. The running gear utilizes computer-controlled active suspension for a smoother, safer ride, and anti-yaw dampers are fitted between cars for improved stability [1]. All sixteen cars in each train are powered, giving a maximum of 18.24 MW of power (25,000 hp). Each train costs an estimated ¥5 billion. Because of that pricetag, only nine were built.
          Visually they are quite striking, with a long, pointed nose more like that of a supersonic plane than a conventional high speed train. In 1990, Hitachi commissioned Neumeister Design of Germany to create an exterior and interior design for a new Shinkansen. It became the basis for the development of the 500 Series.
          The first set was delivered for testing in 1995, entering passenger service in March 1997. The entire fleet of nine sets was delivered by 1998. Besides the premium Nozomi services and the current Kodama services, full-length trains are also currently used on Hikari Rail Star services during the busy holiday periods.
        collection: [ Shinkansen, Trains, High Speed Rail, Japan ]
      Dead Fantasy Full HD:
        match:
          title: Dead Fantasy Full HD (Parts 1 - 6)
        sort_title: Dead Fantasy Full HD (Parts 1 - 6)
        title: Dead Fantasy (Parts 1 - 6)
        originally_available: 2007-03-12
        summary: |
          Source: Gametrailers.com
          Creator: Montyoum
          Description: Dead Fantasy is a CGI crossover Fan Film action series made by Monty Oum, previously known at the time for Haloid, another crossover video. It stars the casts of Dead or Alive (+ Ninja Gaiden) and Final Fantasy (+ Kingdom Hearts) beating the stuffing out of each other in the most awesome ways imaginable.
        collection: [ Gaming ]
      DJI - Introducing the Spreading Wings S1000:
        match:
          title: DJI - Introducing the Spreading Wings S1000
        sort_title: DJI - Introducing the Spreading Wings S1000
        title: DJI - Introducing the Spreading Wings S1000
        originally_available: 2014-01-23
        summary: |
          Source: YouTube
          Creator: DJI
          Description: The S1000 has been specially designed for high level professional aerial photography and cinematography. It comes with retractable landing gear, as well as folding frame arms and propellers to minimize storage space. Every detail has been designed with the needs of creators in mind, helping them to realize their vision while its light weight offers them a longer flight time.
        collection: [ Drone, Aerials, DJI ]
      Amtrak Announces Next Gen HSR:
        match:
          title: Amtrak Announces Next Gen HSR
        sort_title: Amtrak Announces Next Gen HSR
        title: Amtrak Announces Next Gen HSR
        originally_available: 2016-01-01
        summary: |
          Source: YouTube
          Creator: Amtrak
          Description: Video announcing the Amtrak Acela replacement, the Avelia Liberty
        collection: [ Amtrak, Trains, High Speed Rail ]
      Boeing 787-10 Dreamliner and 737 MAX 9 Fly Together:
        match:
          title: Boeing 787-10 Dreamliner and 737 MAX 9 Fly Together
        sort_title: Boeing 787-10 Dreamliner and 737 MAX 9 Fly Together
        title: Boeing 787-10 Dreamliner and 737 MAX 9 Fly Together
        originally_available: 2017-06-16
        summary: |
          Source: YouTube
          Creator: Boeing
          Description: Watch the Boeing 737 MAX 9 and 787-10 Dreamliner soar together as they show off their advanced designs, superior performance and sheer beauty.
          This is a real video of our Boeing 737 MAX 9 and 787-10 Dreamliner being flown by our test pilots. No CG effects were used in any of the footage. Video was captured mostly from a chase plane and helicopter as our newest airplanes flew together for the first time over beautiful Washington State earlier this month.
        collection: [ Boeing, Aircraft ]
      Boeing Prepares the 787-9 Dreamliner for the 2015 Paris Air Show:
        match:
          title: Boeing Prepares the 787-9 Dreamliner for the 2015 Paris Air Show
        sort_title: Boeing Prepares the 787-9 Dreamliner for the 2015 Paris Air Show
        title: Boeing Prepares the 787-9 Dreamliner for the 2015 Paris Air Show
        originally_available: 2015-06-11
        summary: |
          Source: YouTube
          Creator: Boeing
          Description: Watch as Boeing's expert crew rehearses their 2015 Paris Air Show flying display.
        collection: [ Boeing, Aircraft ]

# TITLE:
#   match:
#     title: TITLE
#   sort_title: TITLE
#   title: 
#   originally_available: YYYY-MM-DD
#   summary: |
#     Source: 
#     Creator: 
#     Description: 
#   collection: [  ]
