apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: jovian-prod
  labels:
    app: it-tools
    service: tools
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: it-tools
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      nodeSelector:
        connection: standard
      containers:
      - name: it-tools
        image: ghcr.io/corentinth/it-tools:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: it-tools-http
          protocol: TCP