apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
  namespace: jovian-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: immich
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: immich
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        gpu: rtx4060
      containers:

      # Immich Front End
      - name: immich
        image: ghcr.io/immich-app/immich-server:v2.7.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2283
          name: immich-http
          protocol: TCP
        volumeMounts:
        - name: immich-upload
          mountPath: /usr/src/app/upload
        - name: immich-config
          mountPath: /var/lib/postgresql/data
          subPath: db
        - name: immich-external
          mountPath: /external_libraries
          readOnly: true
        - name: dev-dri
          mountPath: /dev/dri
          readOnly: true
        - name: local-time
          mountPath: /etc/localtime
          readOnly: true
        env:
        - name: TZ
          value: 'America/Chicago'
        - name: NVIDIA_VISIBLE_DEVICES 
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,video,utility
        - name: UPLOAD_LOCATION
          value: '/usr/src/app/upload'
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: immich_db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: immich_db_password
        - name: DB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: immich_db_name
        - name: DB_DATA_LOCATION
          value: '/var/lib/postgresql/data'
        - name: REDIS_HOSTNAME
          value: 'localhost'
        - name: DB_HOSTNAME
          value: 'localhost'
        - name: 'IMMICH_IGNORE_MOUNT_CHECK_ERRORS'
          value: 'true'
        resources:
          requests:
            memory: "4Gi"
            cpu: "25m"
          limits:
            memory: "6Gi"
            cpu: "100m"

      # Immich Machine learning
      - name: machine-learning
        image: ghcr.io/immich-app/immich-machine-learning:main-cuda
        imagePullPolicy: Always
        Ports:
        - containerPort: 3003
          name: immich-machine-learning
          protocol: TCP
        volumeMounts:
        - name: dev-dri
          mountPath: /dev/dri
          readOnly: true
        - name: immich-config
          mountPath: /cache
          subPath: model-cache
        env:
        - name: TZ
          value: 'America/Chicago'
        - name: NVIDIA_VISIBLE_DEVICES 
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,utility
        - name: REDIS_HOSTNAME
          value: 'localhost'
        resources:
          requests:
            memory: "600Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "100m"

      # Immich Redis
      - name: redis
        image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: immich-redis
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "25Mi"
            cpu: "25m"
          limits:
            memory: "50Mi"
            cpu: "50m"

      # Immich Database
      - name: database
        image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: 'America/Chicago'
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: immich_db_password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: immich_db_username
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: immich_db_name
        - name: POSTGRES_INITDB_ARGS
          value: '--data-checksums'
        ports:
        - containerPort: 5432
          name: immich-postgres
          protocol: TCP
        args:
          - "-c"
          - "shared_preload_libraries=vectors.so"
          - "-c"
          - 'search_path="$$user", public, vectors'
          - "-c"
          - "logging_collector=on"
          - "-c"
          - "max_wal_size=2GB"
          - "-c"
          - "shared_buffers=512MB"
          - "-c"
          - "wal_compression=on"
        volumeMounts:
        - name: immich-config
          mountPath: /var/lib/postgresql/data
          subPath: db
        resources:
          requests:
            memory: "2Gi"
            cpu: "10m"
          limits:
            memory: "3Gi"
            cpu: "25m"

      volumes:
      - name: immich-config
        persistentVolumeClaim:
          claimName: immich-pvc
          readOnly: false
      - name: immich-upload
        persistentVolumeClaim:
          claimName: immich-upload-smb-pvc
          readOnly: false
      - name: immich-external
        persistentVolumeClaim:
          claimName: immich-external-smb-pvc
          readOnly: true
      - name: dev-dri
        hostPath:
          path: /dev/dri
      - name: local-time
        hostPath:
          path: /etc/localtime

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - plex
            topologyKey: "kubernetes.io/hostname"
