apiVersion: v1
kind: Service
metadata:
  name: convertnow-service
  namespace: jovian-prod
spec:
  selector:
    app: converternow
  ports:
    - port: 80
      targetPort: convertnow-http
      protocol: TCP
      name: convertnow-http
