apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-smb-media-pvc
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-csi-media
  resources:
    requests:
      storage: 72Ti
  volumeName: qbittorrent-smb-media
