apiVersion: batch/v1
kind: Job
metadata:
  name: diagrams-updater
  namespace: jovian-prod
  annotations:
    argocd.argoproj.io/hook: PostSync
    # 2. Deletes the old job resource before a new sync begins to prevent "already exists" errors
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: diagrams-repo-runner
        image: aegisfatedh/diagrams-repo-runner:main
      env:
        - name: GIT_REPO
          valueFrom:
            secretKeyRef:
              name: diagrams-repo-runner-secrets
              key: git_repo
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: diagrams-repo-runner-secrets
              key: git_token
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: diagrams-repo-runner-secrets
              key: git_username
        - name: DRY_RUN
          value: "no"
      restartPolicy: OnFailure
  # 3. Automatically cleans up the job tracking object inside Kubernetes after 1 hour
  ttlSecondsAfterFinished: 3600