apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-classes
spec:
  project: default
  source:
    path: shared/storage-classes
    repoURL: https://github.com/aegis-fate-gh/homelab-argocd
    targetRevision: main
    directory:
      recurse: true # Set to true to track manifests in subdirectories
      include: '{*.yaml,*.yml}' # Only process these file patterns
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
