apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cronjobs
  finalizers:
  # Delete deployed resources when the Application is deleted
  - resources-finalizer.argocd.argoproj.io
spec:
  project: jovian
  source:
    path: manifests/cronjobs/base
    repoURL: https://github.com/aegis-fate-gh/homelab-argocd
    targetRevision: main
    directory:
      recurse: true # Set to true to track manifests in subdirectories
      include: '{*.yaml,*.yml}' # Only process these file patterns
  syncPolicy:
    syncOptions:
      - Replace=true
  destination:
    namespace: jovian-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
