apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleanuparr-pvc
  namespace: jovian-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-cephfs
  resources:
    requests:
      storage: 5Gi
